/***************************************************************
 * Name:      wxSimpleKnob.h
 * Purpose:   Simple knob widget for wxWidgets
 * Author:    Benoit BOUCHEZ (BEB)
 * Created:   2024-02-01
 * Copyright: (c) Benoit BOUCHEZ
 * License:	  wxWidgets license
 **************************************************************/

#ifndef __WXSIMPLEKNOB_H__
#define __WXSIMPLEKNOB_H__

#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

 // Event generated by this control
const int wxEVT_KNOB_FIRST = wxEVT_FIRST + 5410;

const wxEventType wxEVT_KNOB_CHANGE = wxEVT_KNOB_FIRST + 1;

#define EVT_KNOB_CHANGE(id, fn)	\
		DECLARE_EVENT_TABLE_ENTRY(wxEVT_KNOB_CHANGE, id, -1, \
		(wxObjectEventFunction)(wxEventFunction)(wxCommandEventFunction)&fn, \
		(wxObject*)NULL ),


class WXDLLIMPEXP_CORE wxSimpleKnob : public wxControl
{
public:
	wxSimpleKnob() { Init(); }

	wxSimpleKnob(wxWindow *parent,
		wxWindowID id,
		const wxPoint& pos = wxDefaultPosition,
		const wxSize& size = wxDefaultSize,
		long style = wxBORDER_NONE,
		const wxValidator& validator = wxDefaultValidator,
		const wxString& name = wxButtonNameStr);

	float GetValue() { return fValue; };
	void SetValue(float value);

protected:
	void Init(void);

private:
	DECLARE_DYNAMIC_CLASS(wxSimpleKnob)
	DECLARE_EVENT_TABLE()

	wxWindowID mId;
	float fValue;
	bool MouseInControl;
	bool KnobActive;
	wxSize mSize;

	void OnPaint(wxPaintEvent& event);
	void OnMouse(wxMouseEvent& event);

	void Draw(wxDC& dc);
	void Moved(void);		// Called when knob is moved
};

#endif
